### ISSUE TITLE
build script overflows the stack

### ISSUE THREAD

**Issue by durka** [lalrpop/lalrpop#252]
### STR

```
$ cargo +nightly run ../test/*nll
   Compiling lalrpop v0.13.1
error: failed to run custom build command for `lalrpop v0.13.1`
process didn't exit successfully: `/Users/alex/Programming/rust/nll/nll/target/debug/build/lalrpop-b129642cf7c21e3c/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stdout
processing file `/Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.13.1/src/parser/lrgrammar.lalrpop`

--- stderr

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

No backtrace seems to be available.

### Meta

- rustc 1.20.0-beta.1 (e93aa3aa8 2017-07-18), rustc 1.21.0-nightly (599be0d18 2017-07-26), rustc 1.21.0-nightly (dd53dd5f9 2017-08-01)
- OSX 10.9.5

**Comment by nikomatsakis** [comment]
Hmm. =) What commit of nll was this?

**Comment by durka** [comment]
b844b501a19560e6811960b94f7d97d2ec8961fc. Same results with current master though.

**Comment by yyrust** [comment]
I encountered the same problem when building lalrpop with nightly rust.

After running the build script in lldb, I figured out that the main thread stack size is too small (512k) on OSX and the debug build of lalrpop_snap and lalrpop consumes too much stack space. For example, method `lalrpop_snap::parser::lrgrammar::___parse___Grammar::___reduce()` takes near 300k. It has lots of local variables.

BTW, the release build is fine. (Only if lalrpop is used as a dependency though. When building from source, lalrpop_test fails to compile because of `error[E0601]: main function not found`. But that's another story.)

A possible workaround is to call lalrpop in a child thread which has 2M stack size, but I hope there are better solutions.

**Comment by ahmedcharles** [comment]
Is this a rust bug or a lalrpop bug?

**Comment by nikomatsakis** [comment]
Hmm. So, we have a few options:

- we could use either a child thread or the [stacker crate](https://crates.io/crates/stacker) to insulate ourselves and allocate a bigger stack. This is basically a workaround, but maybe makes sense at least as a stopgap measure.

- we could investigate breaking `reduce` up into smaller functions or otherwise reducing its stack footprint. 
    - the parse-table variant doesn't otherwise use much stack space: the stack is kept in the heap, after all, so I guess it *has* to be reduce.

Maybe it helps to just make a function per reduce action? We would basically be changing this function:

https://github.com/lalrpop/lalrpop/blob/d740f500ba039c8d51658e6d91d432bea1febfbf/lalrpop/src/lr1/codegen/parse_table.rs#L738

so that it generates a separate function for each reduce. Then we would not generate the code inline here but, rather, call that function.

https://github.com/lalrpop/lalrpop/blob/d740f500ba039c8d51658e6d91d432bea1febfbf/lalrpop/src/lr1/codegen/parse_table.rs#L774

Maybe that helps? Worth a try. 

(Note that LALRPOP snap would also have to be regenerated, but that's easy enough.)

@durka or @yyrust can you give some tips on how to measure stack space used by a function, so we can readily tell if it's working?

**Comment by ahmedcharles** [comment]
Does the generated reduce function actually use all of those locals at once? I.e. does Rust reuse stack space for locals which don't overlap? (And if it does, could we have this function take advantage of that?)

**Comment by yyrust** [comment]
@nikomatsakis Here's the script I used in lldb to show stack size for each function:

```
# file name: sss.py
import lldb

def show_stack_size():
    num_frames = lldb.thread.GetNumFrames()
    last_frame = num_frames - 1
    for i in xrange(0, num_frames):
        frame = lldb.thread.GetFrameAtIndex(i)
        if i != last_frame:
            caller_frame = lldb.thread.GetFrameAtIndex(i+1)
            stack_size = caller_frame.sp - frame.sp
        else:
            stack_size = 0
        print('[%d] stack size: %d, stack pointer: %x' % (i, stack_size, frame.sp))
        print('     %s' % str(frame))
```

Usage: run the build script in lldb until it crashes, and then run this script.

For example,
```
(bash) lldb /Users/yyrust/source/lalrpop/target/debug/build/lalrpop-565d1df5928e770b/build-script-build
(lldb) r
(lldb) script import sss.py
(lldb) script sss.show_stack_size()
```

I hope this will help.
