### ISSUE TITLE
Parsing Python: Significant Whitespace

### ISSUE THREAD

**Issue by kjeet** [lalrpop/lalrpop#381]
Hi, new to parsers, new to lalrpop.

Any examples or advice on how to work with significant whitespace?
Is there an example with a custom tokenizers?

Thanks!

**Comment by Marwes** [comment]
A custom lexer would be the only way to do it with LALRPOP. Essentially you want the tokenizer to emit some sort of OPEN_BLOCK and CLOSE_BLOCK tokens whenever the scope is opened/closed due to whitespace and then you can use those tokens to delimit things in the LALRPOP grammar file.

The only parser I am aware of that does this for LALRPOP that I am aware of is the [parser for gluon](https://github.com/gluon-lang/gluon/tree/master/parser/src) which is the language I work on. It is not the easiest code to follow though as the whitespace handling for gluon ended up rather complicated.

**Comment by brendanzab** [comment]
Yeah, I'm planning to do this in Pikelet too: brendanzab/pikelet#12. Hopefully I'll be able to implement it as an intermediate transformation between the lexer and the parser. If I end up with something I'll report back here!
