### ISSUE TITLE
Document custom lexers

### ISSUE THREAD

**Issue by nikomatsakis** [lalrpop/lalrpop#39]
The current tutorial and documentation does not explain how one writes and integrates a custom lexer.

**Comment by mAarnos** [comment]
I am trying to build a parser for the BNF described [here](http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html). If you scroll down enough you notice that the BNF also contains a custom lexer. However, without documentation it is pretty hard to implement it. It would be greatly appreciated if you could finish up the documentation, or alternatively help me in the implementation work.

**Comment by nikomatsakis** [comment]
@mAarnos I should really write up the docs, yes. But in the meantime: do you have a link to what you have attempted? I can show you some examples -- it's actually fairly straightforward.

Basically, you just need to define an enum for your tokens and write up something that implements the `Iterator` trait for those tokens. It depends a bit if you want accurate span (line/column number) information and whether your iterator is fallible (i.e., if there are inputs that cannot be lexed, which is generally true). 

This is the [LALRPOP tokenizer][1], which makes maximal use of all features. [This enum][2] represents each token. Here is [the implementation of the iterator trait][3]. The item type is `Result<Spanned<Tok<'input>>, Error>`: basically, the `Err` case means a lexer error, and the `Ok` case means a successful token. `Spanned` is just an alias for `(Location, Tok<'input>, Location)`, where the first `Location` is the start of the token, and the second is the end of the token. 

Finally, you need a corresponding section in your grammar that tells LALRPOP what your location and error types are, and which variant corresponds to which terminal. Here is the [one LALRPOP uses][4].

[1]: https://github.com/nikomatsakis/lalrpop/blob/d17fdd812731e2794e0196bb21f669534f1e963e/lalrpop/src/tok/mod.rs
[2]: https://github.com/nikomatsakis/lalrpop/blob/d17fdd812731e2794e0196bb21f669534f1e963e/lalrpop/src/tok/mod.rs#L32-L86
[3]: https://github.com/nikomatsakis/lalrpop/blob/d17fdd812731e2794e0196bb21f669534f1e963e/lalrpop/src/tok/mod.rs#L606-L608
[4]: https://github.com/nikomatsakis/lalrpop/blob/d17fdd812731e2794e0196bb21f669534f1e963e/lalrpop/src/parser/lrgrammar.lalrpop#L335-L387

**Comment by nikomatsakis** [comment]
Anyway, let me know if that is helpful, I didn't go into much depth, so please do ask questions.

**Comment by Binero** [comment]
It would be a appreciated if you could briefly explain what are the requirements of a lexer in the library, and how to tell it to use one.

**Comment by nixpulvis** [comment]
I built a custom lexer (heavily based on the LALRPOP lexer) and it seems like most use cases for hand writing lexers could be conved by expanding the LALRPOP language. At first thought I came up with something like this.

```
grammar;

// Same as it is today.

tokens;  // Optional 3rd section.

LBRACK = "[";
IDENT = "[a-zA-Z][a-zA-Z0-9-_]*";

// Something to make building comments and escapes easier.
```

As far as the more complex parts of lexing Yacc allows for lexer states, so you can transition in and out of states like `COMMENT` or `ESCAPE`. This works really nicely in my opinion.

**Comment by Binero** [comment]
Would be nice also to make them ignorable like for example 
```rust
ignorable comment = "\#.*\n";
```

**Comment by nikomatsakis** [comment]
The matter of extending LALRPOP's own lexer generation is #14, not this issue.

**Comment by gnosek** [comment]
I'd love a simple complete example showing how to strip shell-style comments (it's what I'm actually trying to do right now and don't quite know where to start)

**Comment by malleusinferni** [comment]
@gnosek Currently, the only way to do that is to write your own lexer. It should implement the Iterator interface such that `Item` is `Result<(Loc, Token, Loc), Err>` for arbitrary types `Token`, `Loc`, and `Err`, where `Loc` holds offsets into the input string. (I say "arbitrary" but `Token` should be an enum, and `Loc` should just be `usize`.) So, the return value of your next() method will look like this:

    Some(Ok((token_start, Token::SomeToken, token_end)))

...and EOF is represented by `None`. You're probably gonna end up writing this out by hand. Hopefully it will stay under a thousand lines of code. Good luck.

Now, assuming the hard part is out of the way, here comes the weird part. Intuitively, you might think that if you have a Token enum, you can write `Token::Foo` directly in the grammar rules. Not so fast. What you're supposed to do (as far as I can tell) is use string literals as symbolic names to represent your enum values. [You define all these mappings yourself](https://github.com/nikomatsakis/lalrpop/blob/d17fdd812731e2794e0196bb21f669534f1e963e/lalrpop/src/parser/lrgrammar.lalrpop#L335-L387) (reposting @nikomatsakis's link). Thus, if you have some keyword `foo`, you'll write `"foo"` in your grammar rules, and in the bottom section you'll also write `"foo" => Token::Foo`.

So, for example, here's a line from the grammar I wrote today:

    "trace" <Expr> ";" => ast::Stmt::Trace(<>),

And here are the mappings it uses:

    ";" => Tok::EndLn,
    "trace" => Tok::KwTrace,
    // others omitted

Here, my tokenizer produces `Tok::EndLn` in response to a newline as well as an actual semicolon... But the parser doesn't know that, because it doesn't handle the character stream directly. Likewise, all my comment-skipping logic is in the tokenizer, and the parser knows nothing about my comment syntax.

Hope that helps. I was pretty bewildered for a couple hours there.

**Comment by nikomatsakis** [comment]
That's mostly right -- except that you don't have to use string literals, you can use other names too. e.g., `trace => Tok::KwTrace`. But you do have to define a mapping. Moreover, it's quite flexible: for example, you could do `trace => Tok::KwTrace(<u32>, _)`, which would mean that the value of a `trace` token is the `u32` found in the first argument of the enum, and that the second argument should be ignored.

I used to have a kind of short-hand, where you could just use string literals and we assumed that (e.g.) "KwTrace" would be mapped to `Tok::KwTrace`, but I removed it I think. I could add it back, might be handy.

Another option to writing the lexer by hand, btw, is to use a more automated lexer generator such as <https://github.com/LeoTestard/rustlex>. Sadly LALRPOP's doesn't yet support a more flexible input format, mostly because I haven't had time to devote to it (I'd love to work on this with someone :)

**Comment by nikomatsakis** [comment]
I am hoping to push for 1.0 soon, so I do intend to spend a fair amount of time just writing docs at least -- I think this issue should be first on my list.

**Comment by nikomatsakis** [comment]
In the meantime, here is an example of a test that uses a custom lexer:

- https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/error.lalrpop

Notice in particular the `extern` section, which defines the various bits of that lexer. For example, if using the most capable option, the lexer is expected to yield an iterator of `Result<(L, T, L), E>` values, where `L` is a "location" type (usually a `usize`) used to indicate where the token started and ended, `T` is the token type, and `E` is the "error" type. Those various bits are defined in the `extern` section. I think you can just leave out the `type Location` and `type Error` if your lexer either doesn't track locations or doesn't yield errors.

**Comment by nikomatsakis** [comment]
Ah, here is a simpler test that eschews locations and errors:

- https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/expr.lalrpop

And the tokenizer, a very simple one, is here:

- https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/util/tok.rs

LALRPOP's own tokenizer is probably a better model though:

- https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop/src/tok/mod.rs

**Comment by malleusinferni** [comment]
@nikomatsakis Thanks for the clarification! I couldn't catch you on IRC the other day so I was going mainly by guesswork and experimentation. Maybe a tutorial is in order? I'll write something up and send a pull request.

As for my own project, I'd prefer to use a lexer generator to help manage the explosion in complexity once I add interpolated strings. Even if the token stream input format accepted by LALRPOP won't soon be changed, perhaps a convention for writing iterator adapters will suffice. This part will have to go on the back burner, but I'll try some things out later.

**Comment by sbstp** [comment]
I'd like to see documentation on parsing string literals. I'm having trouble parsing them using a grammar. I've searched a bit and it seems like it's a job for the tokenizer, so perhaps it could be a good subject for the tutorial.

**Comment by euclio** [comment]
I'm trying to write a `sh` parser (probably way over my head, but I'm patient) in Rust. I'm wondering if lalrpop is the tool for the job. For my custom lexer, how do I represent context-sensitive tokens [as seen here](http://pubs.opengroup.org/onlinepubs/9699919799/)? My lexer can currently convert tokens into operators, io_numbers and tokens.

However, since further classifying `token` into `word`, `name`, `assignment_word` requires knowing the context of the token (and the grammar itself), I'm not quite sure how to proceed.

**Comment by ahmedcharles** [comment]
It seems like the whitespace tutorial covers this. Should this be closed? Perhaps with the opening of more specific issues for things that may be missing?

**Comment by ahmedcharles** [comment]
Closing. Please reopen (or open a new issue) if there's still something in the docs that is lacking.

**Comment by eduhenke** [comment]
> In the meantime, here is an example of a test that uses a custom lexer:
> 
> * https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/error.lalrpop
> 
> Notice in particular the `extern` section, which defines the various bits of that lexer. For example, if using the most capable option, the lexer is expected to yield an iterator of `Result<(L, T, L), E>` values, where `L` is a "location" type (usually a `usize`) used to indicate where the token started and ended, `T` is the token type, and `E` is the "error" type. Those various bits are defined in the `extern` section. I think you can just leave out the `type Location` and `type Error` if your lexer either doesn't track locations or doesn't yield errors.

When the lexer yields an iterator of `Result<(L, T, L), E>`. Is there any specific reason why the `L` type parameter, is being used twice? I understand that in the simple case where `L=usize`, the first `L` is the start location, and the second `L` is the end location, however couldn't we model that making `L=(usize, usize)`? I am questioning that because I am currently using `L` as:
```rust
struct Location {
    pub span: core::ops::Range<usize>,
    pub file_id: usize,
}
```

And this type already encapsulates the idea of a text range. It is a bit weird to have this value duplicated twice, just because of the typing where it was assumed that `L` was a more simpler type like `usize`.

**Comment by Marwes** [comment]
> I understand that in the simple case where L=usize, the first L is the start location, and the second L is the end location, however couldn't we model that making L=(usize, usize)

That may be better, not aware of any problems with changing it.
