### ISSUE TITLE
Ambiguity between unrelated terminals.

### ISSUE THREAD

**Issue by theindigamer** [lalrpop/lalrpop#390]
I'm not sure why the following generates an error:

```
grammar;
Foo: i32 = <s:r"0"> => 0;
Bar: i32 = <s:r"(-)?0"> => 0;
```

So long as I'm not using both the terminals on the LHS of the same production, it shouldn't be an error, right?

What I was trying to do was write regexes for naturals and integers (as only naturals are allowed in some places) but that gave me a similar error.

**Comment by KnownVermicelli** [comment]
Problem is that lexer can't decide which token it should use. If "-" is the only difference then "0" would match both of these with the same lenght (if there is multiple match then longest one wins).

I guess that by now you've solved your problem but here's my solution:
keep Foo as it is, but instead of Bar use:

`Bar: i32 = {
    (-)? Foo => 0,
}`

(Haven't really checked syntax but you get the idea).

**Comment by theindigamer** [comment]
Yes, I later understood why the problem was arising -- I was under the wrong impression that there is no lexer, it just parses things directly, which is something you do when you're working with parser combinators. Regardless, thanks for pointing it out :)
