### ISSUE TITLE
warning: literal out of range for i8

### ISSUE THREAD

**Issue by tekknolagi** [lalrpop/lalrpop#394]
Hi,

I just encountered a strange warning when building my grammar. The output of the compiler is as follows:

```
willow% cargo test
   Compiling tablam-lang v0.1.0 (file:///home/max/Documents/Dev/tablam/lang)
warning: literal out of range for i8
     --> /home/max/Documents/Dev/tablam/target/debug/build/tablam-lang-2b9170cb7aa5f391/out/tablam.rs:40947:13
      |
40947 |             128 => {
      |             ^^^
      |
      = note: #[warn(overflowing_literals)] on by default
.
.
.
```

I think this is due to the `action` jump table using an `i8` and me... having too many actions? I'm not sure. I'm new to this sort of thing.

In any case, I have attached the lalrpop grammar ([here](https://gist.github.com/489dedfaab2e699c6dcaba1bd197b330)) and the resulting Rust parser ([here](https://gist.github.com/8a43eae8e4626e050535df3eba3fd3dd) -- warning: LARGE (~2M)).

Please let me know if I can provide any more information.

Cheers,
Max

**Comment by Marwes** [comment]
Whelp, seems I made a mistake here https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/lr1/codegen/parse_table.rs#L350-L351 . There shouldn't be a `- 1` since we end up negating the reduce action which means that reduce actions should also be limited to 127 when using `i8`.

(Or we could avoid the negation and match on the negative numbers instead I guess).
