### ISSUE TITLE
Feature request: optional crate feature to generate no_std parser 

### ISSUE THREAD

**Issue by polaris64** [lalrpop/lalrpop#397]
I'm writing a language parser and interpreter for a `no_std` environment and I have chosen to use LALRPOP as the parser generator.  While I have made sure my grammar definition and interpreter both only use types from `core` and `alloc`, the parser generated by LALRPOP includes standard library elements (`std::vec::Vec`, `std::option::Option`, etc.)

Would it be possible to add a feature to LALRPOP where the generated parser does not use types from the standard library, thus making the parser usable in `no_std` crates?

**Comment by Marwes** [comment]
For recursive descent parsers this might be as easy as changing these lines to refer to `core::marker::PhantomData` https://github.com/lalrpop/lalrpop/blob/b01b0326228251bed799545444de8be164d355a7/lalrpop/src/lr1/codegen/base.rs#L262-L278 .

Parse table parsers are a bit trickier since they also need `Vec`, but I'd imagine an attribute could be added which lets one define a path to a `Vec`-like type or something.

**Comment by polaris64** [comment]
OK that's good to know.  I'll modify the relevant codegen modules accordingly and I'll report back.  If that all works then I'd suggest adding a crate feature to make these alterations conditional.

**Comment by polaris64** [comment]
Sorry for the delay in getting back to this.  I spent some time modifying the codegen modules but unfortunately I ran out of time before I could get everything done completely.

I'm sure it will be possible, so perhaps someone else would like to take over for now?  If I get some spare time I will try to continue, but I cannot guarantee that this will be any time soon.
