### ISSUE TITLE
Compiling lalrpop in nightly fails

### ISSUE THREAD

**Issue by pudnax** [lalrpop/lalrpop#625]
I got this error trying to compile [Nuance](https://github.com/Gui-Yom/nuance). I hope it's not some bug from the deep ends of rustc?

```Bash
   Compiling lalrpop v0.19.6
Basic Block in function '_ZN7lalrpop3tok9Tokenizer10take_until17h0bd071834c950b73E' does not have terminator!
label %9
in function _ZN7lalrpop3tok9Tokenizer10take_until17h0bd071834c950b73E
LLVM ERROR: Broken function found, compilation aborted!
```

OS: Manjaro 21.1.1 Pahvo
Kernel: x86_64 Linux 5.10.60-1-MANJARO
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.56.0-nightly (0035d9dce 2021-08-16)

**Comment by Marwes** [comment]
Looks like a rustc bug

**Comment by seniorjoinu** [comment]
+1 on this

Ubuntu 21.04
5.11.0-31-generic
rustc 1.56.0-nightly (2d2bc94c8 2021-08-15)

**Comment by agg23** [comment]
Switched to using nightly-2021-07-29 to keep `rls` support.

**Comment by nixpulvis** [comment]
I was running into this issue, then upgrading to `1.57.0-nightly (485ced56b 2021-10-07)` fixed my issue. I seem to recall hitting this issue before and running the latest nightly fixed it. It seems to me like something getting out of sync with the LLVM versions, but since rustc maintains its own fork (right?) I'm not exactly sure how this is possible, so maybe I'm wrong about that.
