### ISSUE TITLE
Renaming acronyms names to meet Rust conventions before 1.0

### ISSUE THREAD

**Issue by youknowone** [lalrpop/lalrpop#740]
- NFA -> Nfa (type)
- DFA -> Dfa (type)
- EOF -> Eof (enum)
- LR -> Lr (type)
- NT -> Nt (type)

This is breaking change because they are exposed as public types.
If we have desire to change the names fit for common conventions, making it before 1.0 will be better than later.
The previous names will be type aliases and const as `#[deprecated]` marked for backward compatibility.

# Unresolved questions
- Do we want to change the names?

# References
- https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms

**Comment by nikomatsakis** [comment]
Yep, we should do that.

**Comment by nwalfield** [comment]
I apologize if this sounds ungrateful.  That's not my intent.  I'm very appreciative of the work that goes into lalrpop.

From our (Sequoia PGP's) perspective, this is an unfortunate change.  This changes lalrpop's API in a way that we need to change our code (specifically: `s/ParseError::UnrecognizedEOF/ParseError::UnrecognizedEof/`).   Until now, we've managed to depend on lalrpop-util as follows:

```
lalrpop-util = ">=0.17, <0.20"
```

Because of this change, we can't expand that range, but have to change it to:


```
lalrpop-util = "0.20"
```

Unfortunately, we can't use 0.20, because it raises the MSRV to 1.64 and our MSRV is 1.60.

In principle, I'm fine with breaking an API when there is a tangible benefit.  From my perspective, I don't see the advantage of this change.

**Comment by youknowone** [comment]
I am sorry for ParseError incompatibility and inconvenience about it. Scalar enums had const alias but I didn't have a way to make structural variant alias. (it became a hard break unlike other names describe above)

Does sequoia PGP need to support multiple version of `lalrpop-util`? That's unlikely to happen for most of cases.
Usually `lalrpop` is used for compile time and `lalrpop-util` is used for runtime. `lalrpop-util` is comparably very small. Having multiple versions of lalrpop-util will not be a big deal.

You can stick on `lalrpop-util = ">=0.17, <0.20"` for a while until you change MSRV. Users will have rare chance to have multiple lalrpop-util on there deps tree. Even if they do, lalrpop-util itself will be small enough.

**Comment by nwalfield** [comment]
Thanks for the explanation.  `sequoia-openpgp`'s MSRV is currently 1.60.  We don't need to support multiple versions of lalrpop, but we do need to ensure that a version that we support has an MSRV of 1.60.  Our general policy is to have an MSRV of the `rustc` in Debian stable as long as possible.  When that becomes too inconvenient, we switch to Debian testing.  Currently, Debian testing is at 1.63 so in principle we'd be willing to bump our MSRV to 1.63.

Of course, we don't want to be stuck on old versions of code particularly if there are security issues.  For us, it would be great if either the MSRV were lowered, or there was a commitment to backport security fixes to an LTS branch.
