### ISSUE TITLE
Define MSRV for 1.0

### ISSUE THREAD

**Issue by youknowone** [lalrpop/lalrpop#742]
What will be the minimum supported rust version requirement of lalrpop? By looking CI, it looks like just `stable`.
That can be fine. But documenting will be a good idea.

- Our MSRV: Current stable version of Rust https://github.com/lalrpop/lalrpop/issues/742#issuecomment-1518503250
- [ ] Update cargo.toml
- [ ] Update contributing.md
- [x] Update CI to run on matching rust version

**Comment by youknowone** [comment]
@Pat-Lafon  That sounds like a good suggestion.

**Comment by Pat-Lafon** [comment]
I believe the msrv can also be specified in the `cargo.toml`, maybe add that to checklist?

**Comment by Pat-Lafon** [comment]
I missed the `#[default]` suggestion aswell in #744, this was introduced in 1.62... just of note.

**Comment by youknowone** [comment]
I'd like to suggest to mark 1.60 as current MSRV and listen more users' feedback before going to 1.0.
There are only 6 months gap after the 2021 edition, but will prohibit lalrpop users to have fragmented copies of `regex` from their dependency tree.

We can make it back or forward later before actually mark 1.0 - though backward will be a bit painful.

cc @nikomatsakis @yannham

**Comment by youknowone** [comment]
One of my wishlist is this one: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds

**Comment by nikomatsakis** [comment]
I would not want to hold ourselves to the same standard as regex, personally. I'm not a big fan of old MSRVs. We don't backport security requirements and I don't think that people should use older builds. I recognize that just declaring stable is a bit aggressive. I would be more inclined to do something like "N-2" -- i.e., we track stable, but we hold off on adopting newer features gratuitously.

**Comment by youknowone** [comment]
That sounds good enough. I will remove 1.60 build from CI and add the stable policy to Readme.
N-2 looks good enough to add message to pull request template rather than readme.

**Comment by yannham** [comment]
My two cents: I think specifying `n-2` as a MSRV while it's not actually strictly required kinda defeats the purpose of a MSRV. People should use latest Rust of course, but it's hard to know what constraints they have, which might be crazy but legit (I don't have a good example in mind but you surely find this person who is running Nix on a PowerPC machine which can't use LLVM higher than `X.Y.Z` because the package is broken so they have to cap the version of `rustc` etc. etc.). And it also doesn't really sound like the purpose of MSRV, which is not an advice but really what is this actual minimal version you need to build and run LALRPOP.

On the other hand, maintaining and bumping the MSRV is an additional burden, so that could actually be a better reason (IMHO) to define an MSRV. But in this case having a rolling MSRV feels a bit artificial: is this any better than not specifying an MSRV at all?

Also, MSRV can be bypassed by a simple `--ignore-rust-version`, so there's an escape hatch. But I guess my point is that, if our MSRV is lying (in that it's not actually a MSRV but just a deterministic function of current stable at the time of release), is it really useful? (I'm genuinely asking, it's not a rhetorical question :slightly_smiling_face: )

**Comment by dburgener** [comment]
I think the intent behind MSRV is not to state a policy or future commitment about supporting a particular rust version going forward.  I think it's supposed to be a state of the code right now, so that a user compiling who gets compile errors knows it's because they have an out of date compiler and the code requires newer features.

To that end, we should set our rust version to whatever the minimum version of rust can compile lalrpop right now (I'm guessing 1.62 for #[default], but cargo msrv can tell us for sure).

Separately lalrpop can have a policy about generally not depending on compiler features more recent than toolchain version n-2, but I don't think that means lalrpop should push its msrv forward to n-2 unless/until it actually depends on more recent features.

**Comment by Pat-Lafon** [comment]
@yannham I think the example your looking for here is usually Debian stable which is notoriously conservative. Currently at Rust 1.48, while testing 1.63 https://tracker.debian.org/pkg/rustc. However, I think most users are usually on/around stable... I'm not sure where more recent data is but there are results posted for the Rust 2021 survey https://raw.githubusercontent.com/rust-lang/surveys/main/surveys/2021-annual-survey/2021-annual-survey-summary.pdf.

I think one thing that isn't wanted is to be in a situation where this is rehashed over and over with pr's both for potential new features, or replacing code to maintain a specific version.

I agree that having a lying msrv is probably a bad idea(I'm ok with not including it in the toml to decrease maintenance burden and then letting the Rust compiler figure it out but I think @dburgener's point is well taken around error messages).

> Separately lalrpop can have a policy about generally not depending on compiler features more recent than toolchain version n-2, but I don't think that means lalrpop should push its msrv forward to n-2 unless/until it actually depends on more recent features.

Yeah, it's just to say that it is always ok to add new features that use `rust-version <=  n-2` and the msrv is adjusted to where ever that is.

**Comment by nikomatsakis** [comment]
Giving an accurate MSRV but documenting our willingness to adopt (relatively) new features seems good. Can cargo msrv test accurately so that we know we need to update?

**Comment by Pat-Lafon** [comment]
I believe so with "`cargo msrv verify` to verify the MSRV as specified by a crate author"

**Comment by youknowone** [comment]
`cargo msrv` is a bisect tool to find msrv. I used `cargo msrv` to check our current state. But when other contributors update it next time, they will find their own minimum version.

@nikomatsakis I tried to make that suggestion in https://github.com/lalrpop/lalrpop/pull/763/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R17-R21
Please leave a comment if it doesn't fit well.
