### ISSUE TITLE
Using `ThinVec` instead of `Vec`

### ISSUE THREAD

**Issue by MichaReiser** [lalrpop/lalrpop#800]
Hy

Thanks for working on and maintaining lalrpop. Ruff uses it indirectly via RustPython, and it works great for us. 

We're currently investing how we can improve Ruff's performance (Linter and code formatter). One thing that we want to explore is to replace the `Vec`s in our AST with `ThinVec` (see [AST shrinkage](https://nnethercote.github.io/2023/03/24/how-to-speed-up-the-rust-compiler-in-march-2023.html)). The preliminary results look promising because it significantly reduces the size of our `Stmt` and `Expr` unions. However, I fail to understand how to update our grammar to use a `ThinVec` in places where we use the built-in `+` and `*` macros. 

I'm okay rolling our own macros and using them instead of `+` and `*` but haven't yet figured out how to define them to be the equivalent of lalrpop's built-in macros. I'm also wondering if, internally, it would still result in lalrpop copying all entries from a `Vec` to a `ThinVec`. 

Any help would be greatly appreciated. Thank you

Edit the following seems to work but doesn't seem to be any faster for RustPython :(

```
#[inline]
ZeroOrMore<T>: ThinVec<T> = {
    => ThinVec::new(),
    <v:OneOrMore<T>> => v
}

OneOrMore<T>: ThinVec<T> = {
    <e:T> => thin_vec![e],
    <mut v:OneOrMore<T>> <e:T> => {
        v.push(e);
        v
    }
}
```

**Comment by dburgener** [comment]
So, if I understand it right, it looks like the above grammar you specified does what you want, albeit in a less ergonomic manner than with `+` and `*`.  It seems like that doesn't help performance on RustPython, so the original motivator isn't overly needed at this point.  (To answer the question, I'm pretty sure based on lalrpop code inspection that the grammar you posted does exactly what you are looking for.  I think the issue is that ThinVec doesn't provide the desired performance wins, rather than lalrpop internally doing something bad).

The question remains though about redefining `+` and `*` to support other collection types.  Rust doesn't have a `Collection` trait or similar to require there.  `+` and `*` are hardcoded to a Vec, and use the functions `push()`, `new()`, and the `vec!` macro (which is essentially just from()/into()).

Sadly, I think the approach of defining a pub trait in lalrpop doesn't really address the problem, because rust only allows implementing a trait on a type if either the trait or type is local to the crate.  So it wouldn't be possible to address use cases like this, because RustPython implements neither ThinVec nor this hypothetical trait, so it couldn't actually implement lalrpop's trait on ThinVec.

That probably leaves the approach of allowing users to define their own action code for the built-in macros:

```
#[inline]
<T>*: ThinVec<T> = {
    => ThinVec::new(),
    <v:OneOrMore<T>> => v
}

<T>+: ThinVec<T> = {
    <e:T> => thin_vec![e],
    <mut v:OneOrMore<T>> <e:T> => {
        v.push(e);
        v
    }
}
```

Based on a pretty initial code investigation, that looks like a fairly disruptive code change to implement.

A final option might be to expose to users a means to define `new()`, `push()` and `from([<T>])` for their collection as action code, and then substitute that in at code generation for the `+` and `*` code.  Basically essentially a trait, but implemented via lalrpop code generation instead of real traits.  I don't immediately have any good ideas for what that might look like syntactically.

Given that none of these options are really great, the workaround in the OP is really not that bad, and being explicit about "this isn't a vec" might avoid confusion, I'm not sure I see a compelling use case for this feature.

**Comment by yannham** [comment]
>  So it wouldn't be possible to address use cases like this, because RustPython implements neither ThinVec nor this hypothetical trait, so it couldn't actually implement lalrpop's trait on ThinVec.

It's probably obvious for many readers, but for the sake of completeness, it's possible to do so (and at zero-cost at runtime) by using a wrapper type:

```rust
pub struct MyThinVecWrapper(pub MyThinVec);

impl WhateverTraitIWant for MyThinVecWrapper { }
```

It's just a bit unergonomic. But you could implement Lalrpop's trait on the wrapper, get a `MyThinVecWrapper` out of Lalrpop, and do the obvious conversion to `ThinVec` on the fly when building the AST. All of this code will be optimized away with very high confidence.

That being said, having a trait inside Lalrpop has the other issue of not being standard: who knows how many other crates define a trait which would be isomorphic to an hypothetical Lalrpop's one (it's basically just a monoid, a simple structure which tends to pop up a lot). But I don't know if there's much we can do, as long as the Rust stdlib doesn't feature such a trait (or as long as there isn't a standard set by a well-established external crate).

**Comment by MichaReiser** [comment]
Thanks. Using our own "special" grammar seems reasonable to me. 

The only thing I noticed (but didn't invest time in) is that I wasn't able to use `OneOrMore` in all places where I used `+` before because the grammar than suddenly became ambiguous. This would indicate that there's at least a small semantical difference (Maybe it's just that lalrpop can better reason about +)?

Thanks for your explanations. I'm closing because there's a viable solution.
