### ISSUE TITLE
Confusion about Ambiguous regex

### ISSUE THREAD

**Issue by underwoodtan** [lalrpop/lalrpop#838]
This will cause an error:
```
Test:u32 = {
  <r"[1-9]+"> r"begin" => {<>...},
  <r"[0-9]+"> r"end"   => {<>...},
}
```
error: ambiguity detected betwee
n the terminal `r#"[1-9]+"#` and the terminal `r#"[0-9]+"#`

  --- stderr
      <r"[1-9]+"> "begin" => 1,
       ~~~~~~~~~
This will pass.
```
Test:u32 = {
  <r"[0-9]+"> r"begin" => {<>...},
  <r"[0-9]+"> r"end"   => {<>...},
}
```
So I had to write something like this, and add regex match in the custom code to get the number.
```
Test:u32 = {
  <r"[1-9]+\s*begin"> => {...},
  <r"[0-9]+\s*end">   => {...},
}
```
Is this a bug, or it's a feature。If it's a feature, is there any better way to get the number?

**Comment by dburgener** [comment]
I would call it a "limitation" rather than either bug or feature.

The reason it works like this is because lalrpop processes input in two phases, first lexing then parsing.  The role of lexing is to turn the input into a stream of tokens, and the parsing is to structure those tokens.  Lexing looks at all the non-terminals in the grammar, and then turns the input into a sequence of those non-terminals.  So the lexer needs to know which bucket to put a digit number in (either "[0-9]+" or "[1-9]+" before the parser looks at it to know if it's followed by "begin" or "end".  (And note that in more elaborate grammars where it isn't the immediate next token, it may not be possible in LR(1) in general to handle this sort of situation)

There are a few ways to address this.  The lalrpop book [mentions](https://lalrpop.github.io/lalrpop/lexer_tutorial/001_lexer_gen.html#ambiguities-between-regular-expressions) specifiying precedence via a match expression, which can allow you to have both the 0-9 and the 1-9 nonterminal in the same grammar, but that won't really help here, since you care about what follows them.

What you wrote does of course work, but as you point out is pretty unpleasant.  I would handle this by treating "0" as a special case, either in the 1-9 situation, or the 0-9 situation.  In other words, Either match both on the 0-9 nonterminal, and then explicitly check for the presence of 0 in the action code for the "begin" block and [return a user parse error](https://lalrpop.github.io/lalrpop/tutorial/007_fallible_actions.html) on failure, or match both on the 1-9 nonterminal, and also add a "0" "end" special case.
