### ISSUE TITLE
Parsing from standard input?

### ISSUE THREAD

**Issue by metageek** [lalrpop/lalrpop#847]
I'm building a little Lisp, for practice, and I want to have a REPL (interactive evaluation of what's typed at the prompt); but I can't see any way to parse from standard input. It looks like `parse()` only accepts strings. It could parse from a file, by reading the whole file into a string; but that doesn't give me interactivity.

Apologies if this has been asked before; I couldn't find it by search for "standard" or "stdin".

Thanks!

**Comment by yannham** [comment]
I think the usual approach to write a REPL is: read input until "end" (whatever ends mean; it can be `Enter`, EOF as `Ctrl+C`, etc.), parse, evaluate, print the result, and accept a new input. As such, I don't think you need more than parsing strings from LALRPOP. You just have to read the input into a `String` separately before, and call `parse`. To do the former, you can use a crate such as [rustyline](https://github.com/kkawakam/rustyline).

You can take a look at how it's done e.g. in [Nickel](https://github.com/tweag/nickel/blob/master/core/src/repl/rustyline_frontend.rs). There is a bit more fuss because it also supports commands that aren't code (like `:exit`), but it's still pretty simple, and at some point calls to `repl.eval_full` (https://github.com/tweag/nickel/blob/fe66a02bded97bb804521a79b2272ad1591f807c/core/src/repl/rustyline_frontend.rs#L126) which is a function that takes a string and do in particular the parsing.

What would be the advantage of being able to feed `stdin` directly to LALRPOP? The only two that I can see are: avoid additional String allocation (but honestly, I can't see a situation where it's impactful when you interact with a slow terminal), or that it could error out earlier, if an unknown token is entered for example.

If you really want to, I believe you could use a custom lexer. Then, `parse` takes the lexer as an argument, and you could make your lexer such that it ingests data from a stream like `stdin`. But you'll now have to handle explicitly all tokens of your grammar, which can be quite a lot of boilerplate.

**Comment by metageek** [comment]
> I think the usual approach to write a REPL is: read input until "end"

Yeah, I can do that. Lisp REPLs generally read until the end of an expression, which is easy to find (match parens, skip strings).

> You can take a look at how it's done e.g. in [Nickel](https://github.com/tweag/nickel/blob/master/core/src/repl/rustyline_frontend.rs).

Thanks.

> What would be the advantage of being able to feed `stdin` directly to LALRPOP? The only two that I can see are: avoid additional String allocation (but honestly, I can't see a situation where it's impactful when you interact with a slow terminal), or that it could error out earlier, if an unknown token is entered for example.

You're right, the input is unlikely to get very large on stdin. However, for file input, being able to parse a file without loading it all into memory can be a good thing on large files—and being able to parse from a `Reader` would give us parsing from stdin for free.

> If you really want to, I believe you could use a custom lexer.

Thanks, I'll keep that in mind.
