### ISSUE TITLE
Help with parsing error

### ISSUE THREAD

**Issue by arg0d** [lalrpop/lalrpop#904]
Hey, I'm struggling to understand what is wrong with this grammar. I stumbled across this when working with a full grammar, but ended up bisecting, trying to understand why the full grammar is not working. Why doesn't this grammar parse? `aaaaaaaa` is not referenced by the public nonterminal, yet somehow it influences how `Test` nonterminal is being parsed?

```
called `Result::unwrap()` on an `Err` value: UnrecognizedToken { token: (0, Token(1, "something"), 9), expected: ["r#\"something\"#"] }
```

```Rust
// sometest.lalrpop
grammar;
pub Test = r"something";
aaaaaaaa = "something";
```

```Rust
// main.rs
use lalrpop_util::lalrpop_mod;

lalrpop_mod!(sometest);

#[test]
fn calculator1() {
    sometest::TestParser::new().parse("something").unwrap();
}
```

**Comment by yannham** [comment]
Hello,

Your public rule is actually a terminal, because it's a fixed string literal. So it'll end up being a token in the generated lexer. The same is true for the `aa...` rule. Note that lexing happens before any parsing, so LALRPOP has to decide when seeing `something` if it's an `aa...` token or a `Test` token. Fixed strings have precedence over regexp, so most probably `"something"` is always parsed as an `aa...` token, and thus never matches the public rule `Test`.

This point around lexing, terminals vs non terminals and fixed strings versus regex is explained in the manual, see https://lalrpop.github.io/lalrpop/lexer_tutorial/001_lexer_gen.html.

In a real grammar, this often means that you'll have to factor out the common token, something like:

```
Something = "something";

pub Test = Something;
aaaaaaaa = Something;
````

Which should be working fine.

**Comment by arg0d** [comment]
This makes a lot of sense, thanks!
