### ISSUE TITLE
PermissionDenied when unwritable subdirectories contain *.lalrpop

### ISSUE THREAD

**Issue by dkg** [lalrpop/lalrpop#908]
https://bugs.debian.org/1069212 shows a problem i'm having on debian systems, where a common build practice is to have a link farm within `./debian/cargo_registry` that points back to a bunch of directories in `/usr/share/cargo/registry`.

lalrpop's `build.rs` seems to want to traverse down through the current directory and try to tinker with any file named `*.lalrpop`.

Since the normal user can't write to anything in `/usr/share/cargo/registry`, this yields a PermissionDenied error.

I'm not sure what the right fix is, but if lalrpop would instead hunt for `*.lalrpop` files in `./src/` instead of all of `./` it would make the problem go away for me for now ☺

I'm open to other suggestions.

**Comment by dkg** [comment]
@decathorpe observed that `build/mod.rs.html` lines 56-62 are where the recursive directory walk starts in `.` and not in `./src`

**Comment by decathorpe** [comment]
Yes. It is slightly confusing to me is why session.in_dir and root_dir are different paths at all:
https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/build/mod.rs#L55-L60

This results in the recursive directory walk finding all .lalrpop files under $PWD instead of $PWD/src, which seems to be the actual intention?

**Comment by dburgener** [comment]
A few initial thoughts.  Curious what others think on this one:

* The term "root_dir" in `build/mod.rs` `process_dir()` is a little misleading.  It's the "root" in the sense of "root to search from" rather than "project root", whereas in `api/mod.rs` "root" generally means "project root".  The behavior of `build::process_dir()` is to check the path passed in from the parent, which in the common case comes from `api::process_root()`, which uses the current dir (ie not src)
* The "current dir" behavior is both implied by the name `process_root()` and is specified in the [lalrpop documentation](https://docs.rs/lalrpop/0.20.2/lalrpop/fn.process_root.html)
* Users (such as sequoia) that prefer to process in the src dir should be able to achieve that today with `Configuration::new().use_cargo_dir_conventions().process()` in their `build.rs`
* The `session.in_dir` vs path interplay is pretty confusing.  Looking through #280, it seems as though the focus when `in_dir` was added was really on the `out_dir` side of things.  In particular [this](https://github.com/lalrpop/lalrpop/blob/f79a1a920bd2244287804f61f07ad79362cc5105/lalrpop/src/build/mod.rs#L120-L125) seems kind of weird to me.  That's sort of tangential to the issue at hand though, and I haven't looked into it deeply.
* It's weird that our public usability function `process_root()`, which is also the approach recommended in the documentation, searches from the root instead of `./src`.  I would agree that the vast majority of users probably want the `./src` behavior instead.

My initial reaction, therefore is that we should consider introducing a new `process_src()` public api helper, that searches for `.lalrpop` files in `./src`, and update our documentation to recommend the use of that function rather than `process_root()`.  I don't think we should change the behavior of `process_root()` because:

1. It's literally in the name of the function
2. It's documented to have the current dir behavior

**Comment by dkg** [comment]
That outcome seems reasonable, @dburgener.  until a release of lalrpop is available with `process_src`, i guess we can encourage packages like https://gitlab.com/sequoia-pgp/sequoia/-/merge_requests/1637 to manually find and traverse their `src` dir to avoid that kind of mistake.

**Comment by Pat-Lafon** [comment]
We now have a LALRPOP release(v0.21.0) with `process_src` so I think this can now be closed. We can reopen if there is more to discuss here.
