### ISSUE TITLE
Introducing Lalrpop Guru on Gurubase.io

### ISSUE THREAD

**Issue by kursataktas** [lalrpop/lalrpop#969]
Hello Lalrpop team,

I wanted to update you that I've added the Lalrpop Guru to Gurubase. Gurubase is a platform that aggregates open-source tools to help developers find information quickly. Lalrpop Guru uses the data from this repo and the data from [docs](https://lalrpop.github.io/lalrpop/) to answer questions. I hope you find it useful.

Here is the link to the Lalrpop Guru: https://gurubase.io/g/lalrpop

I believe Lalrpop users or new starters would find it useful to have a badge or a link to Gurubase in the README.md. I've prepared two examples below:

Example 1 - Just a badge: 
--
[![](https://img.shields.io/badge/Gurubase-ASK%20LALRPOP%20GURU-006BFF)](https://gurubase.io/g/lalrpop)

Example 2 - Separate Section:
--
### ✨ Ask Lalrpop Guru
If you don’t want to get lost in the documentation, you can ask [Lalrpop Guru](https://gurubase.io/g/lalrpop) directly. It’s an AI that focuses on addressing your questions about Lalrpop.
[![](https://img.shields.io/badge/Gurubase-ASK%20LALRPOP%20GURU-006BFF)](https://gurubase.io/g/lalrpop)

If you find it useful, I would be happy to open a PR for this.

Additionally, if you want me to disable Lalrpop Guru in Gurubase, just let me know that's totally fine.

**Comment by dburgener** [comment]
Thanks for letting us know about this resource.

I played with it a little bit, and as with all things AI nowadays, its intermixture of fact and hallucination made the value proposition somewhat hit or miss.  One notable example is that I asked it to implement a json parser in lalrpop.  The parser grammar looked correct at a somewhat quick glance (I didn't try compiling it), but it followed up the parser grammar with detailed instructions on implementing a custom lexer for this parser, which is a bunch of extra work that is totally unnecessary for parsing json - the built in lexer is fine for that task.  I don't really like sending people down the wrong road like that.  I tried a few other questions as well with fairly mixed results.

I imagine there are people who can benefit from this tool, but I don't like advertising a documentation resource that we can't stand behind the accuracy of.  Other maintainers may disagree, but my opinion is that we do not want to add the badge in our repo or imply any official endorsement of Lalrpop Guru, however, I don't have any issue personally with you leaving it enabled so that those who discover it through other means can make their own decisions about whether to use it.

Thanks!

**Comment by kursataktas** [comment]
Thank you for taking the time to review Lalrpop Guru and for allowing it to stay enabled. I'm working on improving the logic behind it, and your feedback has been really helpful. If you're open to it, I'd appreciate hearing your thoughts again after I've made some updates. There's no pressure to add the badge, even if things improve—what's most important to me is your honest feedback.

Thanks again!
