### ISSUE TITLE
Lalrpop quietly fails to compile file after inline or a manual inline

### ISSUE THREAD

**Issue by Ki11erRabbit** [lalrpop/lalrpop#988]
I am working on a language and I ran into an issue where I had a shift conflict. It suggested that I inline one of the non-terminals. I did and it caused it to inline the grammar file in the outputted code, causing Rust to fail to compile due to lalrpop not having the same grammar as Rust. 

I also tried manually inlining the non-terminal but that caused the same error. 

[Here is my grammar file](https://github.com/Ki11erRabbit/strong-brew/blob/main/compiler/src/grammar.lalrpop) and here is a snippet of the problematic code so you know what you are looking for. It is currently manually inlined.
```
Block: Expression<'a> = {
    "{" Lb? <expr:(<Expr> (Lb <Expr>)*)> Lb? "}" => {
        expr
    },
};
```
Feel free to ask any questions.

**Comment by dburgener** [comment]
I tried building your project as it stands now, and there are a lot of compiler errors, which at a glance seem to be bugs in your rust code.  For example, I see that you used the type name RawType in the lalrpop grammar, but that type isn't defined in the rust code.

If I'm going to look into a possible lalrpop bug here, it would be helpful to have a version of the code where everything compiles, then add in the grammar causing the shift conflict with the inline suggestion.  As it is, it looks to me like there were pre-existing bugs in the code, and all inlining did was let lalrpop finish compiling so that rustc could run and generate its bug report.

**Comment by Ki11erRabbit** [comment]
Yeah sorry, I didn't realize it due to my lsp not highlighting the error. There is likely many errors in my code I didn't realize from the lsp choking on the output of lalrpop.

**Comment by Ki11erRabbit** [comment]
It seemed to just be errors in my code, sorry for wasting your time
